language: ruby
script: "bundle exec rake spec"

rvm:
  - 2.1.1
  - 2.0.0

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile

notifications:
  email:
    - fnando.vieira@gmail.com
