language: ruby
script: "bundle exec spec"

rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile

notifications:
  email:
    - fnando.vieira@gmail.com
