language: ruby
sudo: false
cache: bundler
rvm:
- '2.3.0'
- '2.2.4'
gemfile:
- gemfiles/rails_4_2.gemfile
- gemfiles/rails_5_0.gemfile
- Gemfile
notifications:
  email: false
env:
  global:
    secure: vOCWAt9QPpbVRH8M2xowCnu31av1kqjB20nlg24aNrf7rWccNi0Il6KpiiCXkCHeJfFBNGHxBcWehZy0If2FiJEjFv/3IhkxzyMRTB+PkOK3i+PEwdVXawdDhkaBnRFqrslxsb1rcfOlIvVVnqnHEMTYEd+Twpd0d4G7idcv4NQ=
